### ISSUE TITLE
Error compiling: No member named 'exchange' in namespace 'std'

### ISSUE THREAD

**Issue by Dazzid** [zkmkarlsruhe/ofxTensorFlow2#19] opened 2022-06-13 13:17 UTC
I'm trying to compile in MacOsX example_basic, but I'm having this error:
No member named 'exchange' in namespace 'std', in context.h line 78.

` inline context::context(context&& ctx) noexcept :
        tfe_context(std::exchange(ctx.tfe_context, nullptr))
    {
    }`
`   
    inline context& context::operator=(context&& ctx) noexcept {
        tfe_context = std::exchange(ctx.tfe_context, tfe_context);
        return *this;
    }`

I might be missing a step of the installation?

**Comment by danomatika** [comment] 2022-06-13 14:25
We currently require C++14 for the addon.

>I might be missing a step of the installation?

Did you catch the [manual change](https://github.com/zkmkarlsruhe/ofxTensorFlow2/blob/main/README.md#macos) that is required to force this in OF on macOS?

**Comment by danomatika** [comment] 2022-06-13 15:53
>Maybe because I'm using an M1?

No. The error is a compile-time error, not a linker error where architecture comes into play.

What version of OF are you using?

**Comment by Dazzid** [comment] 2022-06-13 17:16
I'm using of_v0.11.2, and that's right, the error appears when I change to c++14.

**Comment by danomatika** [comment] 2022-06-13 18:39
> I'm using of_v0.11.2, and that's right, the error appears when I change to c++14.

Do you do a full project clean before rebuilding after changing anything within the build system?

**Comment by Dazzid** [comment] 2022-06-14 12:55
yes, but the error persists. Do you have this?
MACOSX_DEPLOYMENT_TARGET = 10.9

**Comment by danomatika** [comment] 2022-07-21 08:33
I wouldn’t close this since our releases are based on OF releases and the current release 11.2 has this issue. We do not tests against nightly builds of the current OF git master as it’s too much of a moving target.

Better would be to find the actually change that fixes this and add a note in the readme for what people can do to modify OF 11.2… assuming it’s and easy change.

Please reopen for now.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by Dazzid** [comment] 2022-07-21 08:39
I also opened the question in OF forums, and of_v0.11.2 won't compile in C++14 with an easy change

**Comment by danomatika** [comment] 2022-07-21 18:54
Can you add a link to your forum post?

**Comment by Dazzid** [comment] 2022-07-21 22:18
yes, here it is.
It seems that of_v0.11.0 should be fine 
https://forum.openframeworks.cc/t/need-help-switching-to-c-14/40099

**Comment by danomatika** [comment] 2022-07-21 22:20
If the issue is the C++14 won't work *but* C++17 will, then use C++17. This addon requires a minimum of C++14 but 17 should be fine.

**Comment by danomatika** [comment] 2022-10-20 08:42
I'm closing this for now as I'm not seeing this issue OF 0.11.2 on macOS 12 with Xcode 14.

**Closed by danomatika** 2022-10-20 08:42 UTC
